#!/usr/bin/with-contenv bashio
# ==============================================================================
# 20-neolink-config.sh
# Generates neolink.toml from HA add-on options (/data/options.json)
# Users never need to edit this file manually.
# ==============================================================================
set -e

bashio::log.info "Generating Neolink configuration from add-on settings..."

NEOLINK_PORT=$(bashio::config 'neolink_port')
LOG_LEVEL=$(bashio::config 'log_level')
NEOLINK_RTSP_PASSWORD=$(bashio::config 'neolink_rtsp_password')
CONFIG_FILE="/data/neolink/neolink.toml"

mkdir -p /data/neolink

# Determine if any camera has MQTT features enabled
MQTT_ENABLED=false
CAMERA_COUNT=$(bashio::config 'cameras | length')

if bashio::config.exists 'cameras'; then
    for i in $(seq 0 $((CAMERA_COUNT - 1))); do
        ENABLE_MOTION=$(bashio::config "cameras[${i}].enable_motion")
        ENABLE_BATTERY=$(bashio::config "cameras[${i}].enable_battery")
        ENABLE_PREVIEW=$(bashio::config "cameras[${i}].enable_preview")

        if bashio::var.true "${ENABLE_MOTION}" || \
           bashio::var.true "${ENABLE_BATTERY}" || \
           bashio::var.true "${ENABLE_PREVIEW}"; then
            MQTT_ENABLED=true
            break
        fi
    done
fi

bashio::log.info "MQTT features enabled: ${MQTT_ENABLED}"

# Start writing config
cat > "${CONFIG_FILE}" << EOF
# Neolink configuration - Auto-generated by Reolink UniFi Bridge
# DO NOT EDIT - Changes will be overwritten on restart.
# Configure cameras via the Home Assistant Add-on settings UI.

bind = "0.0.0.0:${NEOLINK_PORT}"
permitted_users = ["admin"]

[[users]]
name = "admin"
password = "${NEOLINK_RTSP_PASSWORD}"

EOF

# Add MQTT broker section if needed
if bashio::var.true "${MQTT_ENABLED}"; then
    cat >> "${CONFIG_FILE}" << 'EOF'
[mqtt]
broker_addr = "127.0.0.1"
port = 1883
credentials = {username = "", password = ""}

EOF
fi

# Generate per-camera configuration
if bashio::config.exists 'cameras'; then
    for i in $(seq 0 $((CAMERA_COUNT - 1))); do
        CAM_NAME=$(bashio::config "cameras[${i}].name")
        CAM_USERNAME=$(bashio::config "cameras[${i}].username")
        CAM_PASSWORD=$(bashio::config "cameras[${i}].password")
        IS_BATTERY=$(bashio::config "cameras[${i}].is_battery_camera")
        ENABLE_MOTION=$(bashio::config "cameras[${i}].enable_motion")
        ENABLE_BATTERY=$(bashio::config "cameras[${i}].enable_battery")
        ENABLE_PREVIEW=$(bashio::config "cameras[${i}].enable_preview")

        # Optional fields
        CAM_ADDRESS=""
        CAM_UID=""
        CAM_CHANNEL=""
        CAM_DISCOVERY=""
        if bashio::config.exists "cameras[${i}].address"; then
            CAM_ADDRESS=$(bashio::config "cameras[${i}].address")
        fi
        if bashio::config.exists "cameras[${i}].uid"; then
            CAM_UID=$(bashio::config "cameras[${i}].uid")
        fi
        if bashio::config.exists "cameras[${i}].channel"; then
            CAM_CHANNEL=$(bashio::config "cameras[${i}].channel")
        fi
        if bashio::config.exists "cameras[${i}].discovery"; then
            CAM_DISCOVERY=$(bashio::config "cameras[${i}].discovery")
        fi

        # Stream settings
        HIGH_W=$(bashio::config "cameras[${i}].stream_high_width")
        HIGH_H=$(bashio::config "cameras[${i}].stream_high_height")
        HIGH_FPS=$(bashio::config "cameras[${i}].stream_high_fps")
        LOW_W=$(bashio::config "cameras[${i}].stream_low_width")
        LOW_H=$(bashio::config "cameras[${i}].stream_low_height")
        LOW_FPS=$(bashio::config "cameras[${i}].stream_low_fps")

        if [ -n "${CAM_ADDRESS}" ]; then
            bashio::log.info "Configuring camera: ${CAM_NAME} (${CAM_ADDRESS})"
        else
            bashio::log.info "Configuring camera: ${CAM_NAME} (UID-based)"
        fi

        # Write camera section
        cat >> "${CONFIG_FILE}" << EOF
[[cameras]]
name = "${CAM_NAME}"
username = "${CAM_USERNAME}"
password = "${CAM_PASSWORD}"
EOF

        # Add address only if set (UID-only cameras don't need it)
        if [ -n "${CAM_ADDRESS}" ]; then
            echo "address = \"${CAM_ADDRESS}\"" >> "${CONFIG_FILE}"
        fi

        # Add optional UID
        if [ -n "${CAM_UID}" ]; then
            echo "uid = \"${CAM_UID}\"" >> "${CONFIG_FILE}"
        fi

        # Add optional channel
        if [ -n "${CAM_CHANNEL}" ]; then
            echo "channel = ${CAM_CHANNEL}" >> "${CONFIG_FILE}"
        fi

        # Add optional discovery method
        if [ -n "${CAM_DISCOVERY}" ]; then
            echo "discovery = \"${CAM_DISCOVERY}\"" >> "${CONFIG_FILE}"
        fi

        # Battery camera optimizations
        if bashio::var.true "${IS_BATTERY}"; then
            bashio::log.info "  Camera ${CAM_NAME}: Battery mode enabled (idle_disconnect, pause on client)"
            cat >> "${CONFIG_FILE}" << 'EOF'
idle_disconnect = true

[cameras.pause]
on_client = true
on_motion = true
motion_timeout = 2.0
EOF
        fi

        # Stream configuration
        cat >> "${CONFIG_FILE}" << EOF

[cameras.stream.main]
name = "mainStream"
permitted_format = "H264"
EOF

        # MQTT configuration for this camera
        if bashio::var.true "${ENABLE_MOTION}" || \
           bashio::var.true "${ENABLE_BATTERY}" || \
           bashio::var.true "${ENABLE_PREVIEW}"; then

            cat >> "${CONFIG_FILE}" << 'EOF'

[cameras.mqtt]
EOF
            if bashio::var.true "${ENABLE_MOTION}"; then
                echo "enable_motion = true" >> "${CONFIG_FILE}"
                echo "motion_topic = \"neolink/{camera_name}/status/motion\"" >> "${CONFIG_FILE}"
            fi
            if bashio::var.true "${ENABLE_BATTERY}"; then
                echo "enable_battery = true" >> "${CONFIG_FILE}"
                echo "battery_topic = \"neolink/{camera_name}/status/battery_level\"" >> "${CONFIG_FILE}"
            fi
            if bashio::var.true "${ENABLE_PREVIEW}"; then
                echo "enable_preview = true" >> "${CONFIG_FILE}"
            fi
        fi

        echo "" >> "${CONFIG_FILE}"
    done
fi

bashio::log.info "Neolink configuration written to ${CONFIG_FILE}"

# Export config path for services
echo "${CONFIG_FILE}" > /var/run/neolink_config_path
