#!/usr/bin/with-contenv bashio
# ==============================================================================
# 20-neolink-config.sh
# Generates neolink.toml from HA add-on options (/data/options.json)
# Users never need to edit this file manually.
# ==============================================================================
set -e

bashio::log.info "Generating Neolink configuration from add-on settings..."

# Read actual port from 05-port-selection.sh, fallback to options.json
if [ -f /tmp/actual-ports.json ]; then
    NEOLINK_PORT=$(jq -r '.neolink' /tmp/actual-ports.json)
else
    bashio::log.warning "actual-ports.json missing — using configured port"
    NEOLINK_PORT=$(bashio::config 'neolink_port')
fi

NEOLINK_RTSP_PASSWORD=$(bashio::config 'neolink_rtsp_password')
CONFIG_FILE="/data/neolink/neolink.toml"

mkdir -p /data/neolink

# ── Check if MQTT is actually available ─────────────────────────────────────
# Only write [mqtt] section if broker is reachable — otherwise neolink won't start
MQTT_AVAILABLE="false"
if [ -f /tmp/mqtt.json ]; then
    MQTT_AVAILABLE=$(jq -r '.available // false' /tmp/mqtt.json 2>/dev/null || echo "false")
fi
bashio::log.info "MQTT broker available: ${MQTT_AVAILABLE}"

# ── Determine if any camera has MQTT features enabled ───────────────────────
MQTT_ENABLED=false
CAMERA_COUNT=$(bashio::config 'cameras | length')

if bashio::config.exists 'cameras'; then
    for i in $(seq 0 $((CAMERA_COUNT - 1))); do
        ENABLE_MOTION=false
        ENABLE_BATTERY=false
        ENABLE_PREVIEW=false
        if bashio::config.exists "cameras[${i}].enable_motion"; then
            ENABLE_MOTION=$(bashio::config "cameras[${i}].enable_motion")
        fi
        if bashio::config.exists "cameras[${i}].enable_battery"; then
            ENABLE_BATTERY=$(bashio::config "cameras[${i}].enable_battery")
        fi
        if bashio::config.exists "cameras[${i}].enable_preview"; then
            ENABLE_PREVIEW=$(bashio::config "cameras[${i}].enable_preview")
        fi

        if bashio::var.true "${ENABLE_MOTION}" || \
           bashio::var.true "${ENABLE_BATTERY}" || \
           bashio::var.true "${ENABLE_PREVIEW}"; then
            MQTT_ENABLED=true
            break
        fi
    done
fi

if bashio::var.true "${MQTT_ENABLED}" && ! bashio::var.true "${MQTT_AVAILABLE}"; then
    bashio::log.warning "MQTT features requested but no MQTT broker available — skipping MQTT config"
    bashio::log.warning "Install Mosquitto Add-on or set mqtt_host in add-on config to enable motion/battery"
fi

# ── Start writing config ─────────────────────────────────────────────────────
cat > "${CONFIG_FILE}" << EOF
# Neolink configuration - Auto-generated by Reolink UniFi Bridge
# DO NOT EDIT - Changes will be overwritten on restart.
# Configure cameras via the Home Assistant Add-on settings UI.

bind = "0.0.0.0:${NEOLINK_PORT}"
permitted_users = ["admin"]

[[users]]
name = "admin"
password = "${NEOLINK_RTSP_PASSWORD}"

EOF

# ── Add MQTT broker section ONLY if both enabled AND available ───────────────
if bashio::var.true "${MQTT_ENABLED}" && bashio::var.true "${MQTT_AVAILABLE}"; then
    # Source MQTT credentials written by 10-mqtt-config.sh
    MQTT_HOST="127.0.0.1"
    MQTT_PORT="1883"
    MQTT_USER=""
    MQTT_PASS=""
    if [ -f /tmp/mqtt.env ]; then
        # shellcheck source=/dev/null
        . /tmp/mqtt.env
    fi

    bashio::log.info "Adding MQTT section: ${MQTT_HOST}:${MQTT_PORT}"

    cat >> "${CONFIG_FILE}" << EOF
[mqtt]
broker_addr = "${MQTT_HOST}"
port = ${MQTT_PORT}
EOF

    # Only write credentials if not empty (anonymous MQTT support)
    if [ -n "${MQTT_USER}" ]; then
        cat >> "${CONFIG_FILE}" << EOF
credentials = {username = "${MQTT_USER}", password = "${MQTT_PASS}"}
EOF
    fi

    echo "" >> "${CONFIG_FILE}"
fi

# ── Generate per-camera configuration ───────────────────────────────────────
if bashio::config.exists 'cameras'; then
    for i in $(seq 0 $((CAMERA_COUNT - 1))); do
        CAM_NAME=$(bashio::config "cameras[${i}].name")
        CAM_USERNAME=$(bashio::config "cameras[${i}].username")
        CAM_PASSWORD=$(bashio::config "cameras[${i}].password")

        # Optional bool fields — default false
        IS_BATTERY=false
        ENABLE_MOTION=false
        ENABLE_BATTERY=false
        ENABLE_PREVIEW=false
        if bashio::config.exists "cameras[${i}].is_battery_camera"; then
            IS_BATTERY=$(bashio::config "cameras[${i}].is_battery_camera")
        fi
        if bashio::config.exists "cameras[${i}].enable_motion"; then
            ENABLE_MOTION=$(bashio::config "cameras[${i}].enable_motion")
        fi
        if bashio::config.exists "cameras[${i}].enable_battery"; then
            ENABLE_BATTERY=$(bashio::config "cameras[${i}].enable_battery")
        fi
        if bashio::config.exists "cameras[${i}].enable_preview"; then
            ENABLE_PREVIEW=$(bashio::config "cameras[${i}].enable_preview")
        fi

        # Optional string fields
        CAM_ADDRESS=""
        CAM_UID=""
        CAM_CHANNEL=""
        CAM_DISCOVERY=""
        if bashio::config.exists "cameras[${i}].address"; then
            CAM_ADDRESS=$(bashio::config "cameras[${i}].address")
        fi
        if bashio::config.exists "cameras[${i}].uid"; then
            CAM_UID=$(bashio::config "cameras[${i}].uid")
        fi
        if bashio::config.exists "cameras[${i}].channel"; then
            CAM_CHANNEL=$(bashio::config "cameras[${i}].channel")
        fi
        if bashio::config.exists "cameras[${i}].discovery"; then
            CAM_DISCOVERY=$(bashio::config "cameras[${i}].discovery")
        fi

        if [ -n "${CAM_ADDRESS}" ]; then
            bashio::log.info "Configuring camera: ${CAM_NAME} (${CAM_ADDRESS})"
        else
            bashio::log.info "Configuring camera: ${CAM_NAME} (UID-based)"
        fi

        # Write camera section
        cat >> "${CONFIG_FILE}" << EOF
[[cameras]]
name = "${CAM_NAME}"
username = "${CAM_USERNAME}"
password = "${CAM_PASSWORD}"
EOF

        # Add address only if set (UID-only cameras don't need it)
        if [ -n "${CAM_ADDRESS}" ]; then
            echo "address = \"${CAM_ADDRESS}\"" >> "${CONFIG_FILE}"
        fi

        # Add optional UID
        if [ -n "${CAM_UID}" ]; then
            echo "uid = \"${CAM_UID}\"" >> "${CONFIG_FILE}"
        fi

        # Add optional channel
        if [ -n "${CAM_CHANNEL}" ]; then
            echo "channel = ${CAM_CHANNEL}" >> "${CONFIG_FILE}"
        fi

        # Add optional discovery method
        if [ -n "${CAM_DISCOVERY}" ]; then
            echo "discovery = \"${CAM_DISCOVERY}\"" >> "${CONFIG_FILE}"
        fi

        # Battery camera optimizations
        if bashio::var.true "${IS_BATTERY}"; then
            bashio::log.info "  Camera ${CAM_NAME}: Battery mode enabled (idle_disconnect, pause on client)"
            cat >> "${CONFIG_FILE}" << 'EOF'
idle_disconnect = true

[cameras.pause]
on_client = true
on_motion = true
motion_timeout = 2.0
EOF
        fi

        # MQTT per-camera config — only if MQTT is actually available
        if bashio::var.true "${MQTT_AVAILABLE}"; then
            if bashio::var.true "${ENABLE_MOTION}" || \
               bashio::var.true "${ENABLE_BATTERY}" || \
               bashio::var.true "${ENABLE_PREVIEW}"; then

                cat >> "${CONFIG_FILE}" << 'EOF'

[cameras.mqtt]
EOF
                if bashio::var.true "${ENABLE_MOTION}"; then
                    echo "enable_motion = true" >> "${CONFIG_FILE}"
                    echo "motion_topic = \"neolink/{camera_name}/status/motion\"" >> "${CONFIG_FILE}"
                fi
                if bashio::var.true "${ENABLE_BATTERY}"; then
                    echo "enable_battery = true" >> "${CONFIG_FILE}"
                    echo "battery_topic = \"neolink/{camera_name}/status/battery_level\"" >> "${CONFIG_FILE}"
                fi
                if bashio::var.true "${ENABLE_PREVIEW}"; then
                    echo "enable_preview = true" >> "${CONFIG_FILE}"
                fi
            fi
        fi

        echo "" >> "${CONFIG_FILE}"
    done
fi

bashio::log.info "Neolink configuration written to ${CONFIG_FILE}"

# Export config path for services
echo "${CONFIG_FILE}" > /var/run/neolink_config_path
