#!/usr/bin/with-contenv bashio
# ==============================================================================
# 30-go2rtc-config.sh
# Generates go2rtc.yaml from HA add-on options (/data/options.json)
# ==============================================================================
set -e

bashio::log.info "Generating go2rtc configuration..."

NEOLINK_PORT=$(bashio::config 'neolink_port')
GO2RTC_PORT=$(bashio::config 'go2rtc_port')
NEOLINK_RTSP_PASSWORD=$(bashio::config 'neolink_rtsp_password')
CONFIG_FILE="/data/go2rtc/go2rtc.yaml"

if [ -n "${NEOLINK_RTSP_PASSWORD}" ]; then
    RTSP_AUTH="admin:${NEOLINK_RTSP_PASSWORD}@"
else
    RTSP_AUTH=""
fi

mkdir -p /data/go2rtc

# Build streams section
STREAMS_YAML=""
CAMERA_COUNT=$(bashio::config 'cameras | length')

if bashio::config.exists 'cameras'; then
    for i in $(seq 0 $((CAMERA_COUNT - 1))); do
        CAM_NAME=$(bashio::config "cameras[${i}].name")
        bashio::log.info "  Adding go2rtc stream: ${CAM_NAME}"
        STREAMS_YAML="${STREAMS_YAML}
  ${CAM_NAME}: rtsp://${RTSP_AUTH}127.0.0.1:${NEOLINK_PORT}/${CAM_NAME}/main
  ${CAM_NAME}_sub: rtsp://${RTSP_AUTH}127.0.0.1:${NEOLINK_PORT}/${CAM_NAME}/sub"
    done
fi

cat > "${CONFIG_FILE}" << EOF
# go2rtc configuration - Auto-generated by Reolink UniFi Bridge
# DO NOT EDIT - Changes will be overwritten on restart.

api:
  listen: "127.0.0.1:1984"
  base_path: ""

rtsp:
  listen: "0.0.0.0:${GO2RTC_PORT}"

log:
  level: warn

streams:${STREAMS_YAML}
EOF

bashio::log.info "go2rtc configuration written to ${CONFIG_FILE}"
